export const AUTH_USER_SUCCESSFUL = "AUTH_USER_SUCCESS";
export const AUTH_USER_FAILURE = "AUTH_USER_FAILURE";
export const AUTH_USER_LOGOUT = "AUTH_USER_LOGOUT";
<<<<<<< HEAD
export const SET_HTTP_MESSAGE = "SET_HTTP_MESSAGE";
=======
export const AUTH_MESSAGES = "AUTH_MESSAGES";
>>>>>>> 065320fe3b8d17511178d43869e52525ef772593
