export const AUTH_USER_SUCCESSFUL = "AUTH_USER_SUCCESS";
export const AUTH_USER_FAILURE = "AUTH_USER_FAILURE";
export const AUTH_USER_LOGOUT = "AUTH_USER_LOGOUT";
export const SET_HTTP_MESSAGE = "SET_HTTP_MESSAGE";
